services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6501:6501"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mybookrental-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AluLibrary2
    command: --bind-address=0.0.0.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
