version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/Backend/MyBookRental.API/Dockerfile
    ports:
      - "6501:6501"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DatabaseType=0
      - ConnectionStrings__ConnectionMySQLServer=Server=db;Database=AluLibrary2;Uid=root;Pwd=root;

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AluLibrary2
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
